export const fiatSwapCurrencies = [
  { label: 'United States Dollar', value: 'USD' },
  { label: 'Euro', value: 'EUR' },
  { label: 'Canadian Dollar', value: 'CAD' },
  { label: 'United Arab Emirates Dirham', value: 'AED' },
  { label: 'Australian Dollar', value: 'AUD' },
  { label: 'Singapore Dollar', value: 'SGD' },
  { label: 'New Zealand Dollar', value: 'NZD' },
  { label: 'Japanese Yen', value: 'JPY' },
  { label: 'Brazilian Real', value: 'BRL' },
  { label: 'Swiss Franc', value: 'CHF' },
  { label: 'Chilean Peso', value: 'CLP' },
  { label: 'Colombian Peso', value: 'COP' },
  { label: 'Czech Koruna', value: 'CZK' },
  { label: 'Danish Krone', value: 'DKK' },
  { label: 'Hong Kong Dollar', value: 'HKD' },
  { label: 'Indonesian Rupiah', value: 'IDR' },
  { label: 'Indian Rupee', value: 'INR' },
  { label: 'South Korean Won', value: 'KRW' },
  { label: 'Mexican Peso', value: 'MXN' },
  { label: 'Norwegian Krone', value: 'NOK' },
  { label: 'Philippine Peso', value: 'PHP' },
  { label: 'Polish Złoty', value: 'PLN' },
  { label: 'Qatari Riyal', value: 'QAR' },
  { label: 'Romanian Leu', value: 'RON' },
  { label: 'Saudi Riyal', value: 'SAR' },
  { label: 'Swedish Krona', value: 'SEK' },
  { label: 'Thai Baht', value: 'THB' },
  { label: 'Turkish Lira', value: 'TRY' },
  { label: 'New Taiwan Dollar', value: 'TWD' },
  { label: 'Vietnamese Dong', value: 'VND' },
  { label: 'South African Rand', value: 'ZAR' },
]

export const banxaPaymentMethodIds = {
  creditCard: 'credit-card',
  applePay: 'apple-pay',
} as const
