steps:
  # Obtain cached images for Container Registry
  # - id: "Caching (1/3) pull dependencies image"
  #   name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args: [
  #           '-c', 'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:dependencies || true'
  #         ]
  - id: "Caching (2/3) pull build image"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
            '-c', 'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:build || true'
          ]
  - id: "Caching (3/3) pull latest image"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
            '-c', 'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest || true'
          ]
    # - id: "Build image (1/3) target: dependencies"
    # name: 'gcr.io/cloud-builders/docker'
    # args: [
    #         'build',
    #         --target dependencies
    #         '-t', 'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:dependencies',
    #         '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:dependencies',
    #         '.'
    #       ]
  - id: "Build image (2/3) target: build"
    name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            --target build
            '-t', 'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:build',
            '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:build',
            '.'
          ]
  - id: "Build image (3/3) target: latest"
    name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
              '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA',
              '-t', 'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest',
              '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest',
              '.'
          ]
  # Push the latest container images to Container Registry
  # - id: "Push image to registry (1/4): dependencies"
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:dependencies']
  - id: "Push image to registry (2/4): build"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:build']
  - id: "Push image to registry (1/4): latest"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest']
  - id: "Push image to registry (1/4): latest (with commit hash)"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--set-env-vars'
    - 'REACT_APP_API_ENDPOINT=${_API_ENDPOINT}'
    - '--set-env-vars' 
    - 'NODE_ENV=${_NODE_ENV}'
images:
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest'
timeout: 900s