steps:
  # Build the container image
  - id: "Pull latest image to use as cache"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
            '-c', 'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest || true'
          ]
  - id: "Build new image" 
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
            '-c',
            'DOCKER_BUILDKIT=1',
            'docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA \
            -t us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest \
            --cache-from us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest .'
          ]
  # Push the latest container image to Container Registry
  - id: "Push latest image to the registry"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest']
  - id: "Push new image to the registry (with commit hash)"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--set-env-vars'
    - 'REACT_APP_API_ENDPOINT=${_API_ENDPOINT}'
    - '--set-env-vars' 
    - 'NODE_ENV=${_NODE_ENV}'
images:
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:$COMMIT_SHA'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/${_SERVICE_NAME}:latest'
timeout: 900s