 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/geyser-app:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/geyser-app:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'geyser-app'
   - '--image'
   - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/geyser-app:$COMMIT_SHA'
   - '--region'
   - 'REGION'
   - '--set-env-vars'
   - 'REACT_APP_API_ENDPOINT=${_API_ENDPOINT},'
   - 'NODE_ENV=${_NODE_ENV}'
 images:
 - 'us-central1-docker.pkg.dev/$PROJECT_ID/geyser-docker-repo/geyser-app:$COMMIT_SHA'