name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: Please enter the URL that helps provide a reproduction of the issue
      placeholder: ex. https://geyser.fund/project/create
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
  - type: textarea
    id: browserversion
    attributes:
      label: "Version of Browser"
      description: What browsers are you seeing the problem on ? Please include version number. 
      placeholder: ex. Chrome 90.0.4430.212
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: "Operating system"
      description: What is the impacted environment ? Please include version number?
      placeholder: ex. Windows 10 / Mac OS 11.3.1 / Ubuntu 20.04
    validations:
      required: true