export enum BeehiivTag {
  TYPE_CREATOR = 'type_creator',
  TYPE_CONTRIBUTOR = 'type_contributor',
  TYPE_CONTRIBUTOR_LARGE = 'type_contributor_large',
  TYPE_SPONSOR = 'type_sponsor',
  STATUS_CREATOR_DRAFT = 'status_creator_draft',
  SRC_IMPORT = 'src_import',
  SRC_COLD_OUTREACH = 'src_cold_outreach',
  SRC_GEYSER_WEBSITE = 'src_geyser_website',
  PREF_GUARDIAN = 'pref_guardian',
  PREF_CREATOR_EMAILS = 'pref_creator_emails',
  IMPACT_FUND_SPONSOR = 'impact_fund_sponsor',
  IMPACT_FUND_GRANTEE = 'impact_fund_grantee',
  IMPACT_FUND_HACKATHONS = 'impact_fund_hackathons',
  CATEGORY_COMMUNITY = 'category_community',
  CATEGORY_EDUCATION = 'category_education',
  CATEGORY_OTHER = 'category_other',
  CATEGORY_CULTURE = 'category_culture',
  CATEGORY_OPEN_SOURCE = 'category_open_source',
  CATEGORY_FILM = 'category_film',
  CATEGORY_CIRCULAR_ECONOMY = 'category_circular_economy',
  CATEGORY_SOCIAL_CAUSE = 'category_social_cause',
  CATEGORY_CONTENT = 'category_content',
  CATEGORY_EVENT = 'category_event',
  CATEGORY_STARTUP = 'category_startup',
  CATEGORY_PODCAST = 'category_podcast',
  CATEGORY_WRITER = 'category_writer',
  CATEGORY_ARTIST = 'category_artist',
  CATEGORY_JOURNALISM = 'category_journalism',
  CATEGORY_GAME = 'category_game',
  CATEGORY_COURSE = 'category_course',
  CATEGORY_COLLECTIBLE = 'category_collectible',
  CATEGORY_CONTENT_CREATOR = 'category_content_creator',
  CATEGORY_MUSIC = 'category_music',
  CATEGORY_HARDWARE = 'category_hardware',
  CATEGORY_APP = 'category_app',
  CATEGORY_ADVOCACY = 'category_advocacy',
  CATEGORY_HUMANITARIAN = 'category_humanitarian',
  CATEGORY_TOOLS = 'category_tools',
  CATEGORY_LOBBY = 'category_lobby',
  CATEGORY_MEETUP = 'category_meetup',
  CATEGORY_HACKER_SPACE = 'category_hacker_space',
  CATEGORY_BITCOIN_PRODUCT_LAUNCHES = 'category_bitcoin_product_launches',
  CATEGORY_LEGAL = 'category_legal',
  CATEGORY_MEDICAL = 'category_medical',
  CATEGORY_FUNDRAISERS = 'category_fundraisers',
  CATEGORY_CAUSES = 'category_causes',
  CATEGORY_BITCOIN_INITIATIVES = 'category_bitcoin_initiatives',
  CATEGORY_TRAVEL = 'category_travel',
}

export enum BeehiivCustomField {
  IMPACT_STORIES = 'impact_stories',
  IMPACT_FUNDS = 'impact_funds',
  PROJECT_SPOTLIGHTS = 'project_spotlights',
  PRODUCT_UPDATES = 'product_updates',
  NEWSLETTER_MONTHLY = 'newsletter_monthly',
}

export type BeehiivNewsletterPreferenceKey = 'newsletterMonthly' | 'productUpdates' | 'projectSpotlights'

export const DEFAULT_BEEHIIV_NEWSLETTER_TAGS = [BeehiivTag.SRC_GEYSER_WEBSITE]
