import { Icon } from '@chakra-ui/react'
import type { IconKey } from '@mdxeditor/editor'
import type { IconType } from 'react-icons'
import {
  PiArrowClockwise,
  PiArrowCounterClockwise,
  PiArrowSquareOut,
  PiCaretDown,
  PiCheck,
  PiCode,
  PiCodeBlock,
  PiColumns,
  PiColumnsPlusLeft,
  PiColumnsPlusRight,
  PiCopySimple,
  PiCube,
  PiDotsThreeOutline,
  PiDotsThreeOutlineVertical,
  PiFileText,
  PiGear,
  PiHighlighter,
  PiImage,
  PiLink,
  PiLinkBreak,
  PiListBullets,
  PiListChecks,
  PiListNumbers,
  PiMarkdownLogo,
  PiMinus,
  PiPencilSimple,
  PiRowsPlusBottom,
  PiRowsPlusTop,
  PiTable,
  PiTextAlignCenter,
  PiTextAlignLeft,
  PiTextAlignRight,
  PiTextB,
  PiTextItalic,
  PiTextStrikethrough,
  PiTextSubscript,
  PiTextSuperscript,
  PiTextT,
  PiTextUnderline,
  PiTrashSimple,
  PiWarningCircle,
  PiX,
} from 'react-icons/pi'

const ICON_ENTRIES: Array<[IconKey, IconType]> = [
  ['undo', PiArrowCounterClockwise],
  ['redo', PiArrowClockwise],
  ['format_bold', PiTextB],
  ['format_italic', PiTextItalic],
  ['format_underlined', PiTextUnderline],
  ['code', PiCode],
  ['strikeThrough', PiTextStrikethrough],
  ['superscript', PiTextSuperscript],
  ['subscript', PiTextSubscript],
  ['format_list_bulleted', PiListBullets],
  ['format_list_numbered', PiListNumbers],
  ['format_list_checked', PiListChecks],
  ['format_highlight', PiHighlighter],
  ['link', PiLink],
  ['add_photo', PiImage],
  ['table', PiTable],
  ['horizontal_rule', PiMinus],
  ['frontmatter', PiFileText],
  ['frame_source', PiCodeBlock],
  ['arrow_drop_down', PiCaretDown],
  ['admonition', PiWarningCircle],
  ['sandpack', PiCube],
  ['rich_text', PiTextT],
  ['difference', PiColumns],
  ['markdown', PiMarkdownLogo],
  ['open_in_new', PiArrowSquareOut],
  ['link_off', PiLinkBreak],
  ['edit', PiPencilSimple],
  ['content_copy', PiCopySimple],
  ['more_horiz', PiDotsThreeOutline],
  ['more_vert', PiDotsThreeOutlineVertical],
  ['close', PiX],
  ['settings', PiGear],
  ['delete_big', PiTrashSimple],
  ['delete_small', PiTrashSimple],
  ['format_align_center', PiTextAlignCenter],
  ['format_align_left', PiTextAlignLeft],
  ['format_align_right', PiTextAlignRight],
  ['add_row', PiRowsPlusBottom],
  ['add_column', PiColumnsPlusRight],
  ['insert_col_left', PiColumnsPlusLeft],
  ['insert_row_above', PiRowsPlusTop],
  ['insert_row_below', PiRowsPlusBottom],
  ['insert_col_right', PiColumnsPlusRight],
  ['check', PiCheck],
]

const ICON_MAP = new Map<IconKey, IconType>(ICON_ENTRIES)

/** Provides project-consistent toolbar iconography for MDX editor controls. */
export const mdxEditorIconComponentFor = (name: IconKey) => {
  const IconComponent = ICON_MAP.get(name) ?? PiDotsThreeOutline
  return <Icon as={IconComponent} boxSize={4} />
}
