import { DialogButton, insertMarkdown$, usePublisher } from '@mdxeditor/editor'
import getVideoId from 'get-video-id'
import { t } from 'i18next'
import { PiXLogo, PiYoutubeLogo } from 'react-icons/pi'

import { useDarkMode, useNotification } from '@/utils'

import { TwitterRegex, validateTwitterUrl } from './validations/twitter.ts'
import { validateYouTubeUrl } from './validations/youtube.ts'

const EMBED_MARKDOWN_PREFIX = '\n\n'
const EMBED_MARKDOWN_SUFFIX = '\n\n'

/** Converts a supported YouTube URL to the iframe markdown persisted by the editor. */
export const createYoutubeEmbedMarkdown = (url: string): string | null => {
  if (!validateYouTubeUrl(url)) {
    return null
  }

  const video = getVideoId(url)

  if (!video.id) {
    return null
  }

  const iframe = `<iframe src="https://www.youtube.com/embed/${video.id}" width="100%" scrolling="no" style="width: 100%; height: 400px; border: 0;"></iframe>`
  return `${EMBED_MARKDOWN_PREFIX}${iframe}${EMBED_MARKDOWN_SUFFIX}`
}

/** Extracts tweet ID from x.com URLs used in markdown embeds. */
export const getTweetIdFromUrl = (url: string): string | null => {
  const match = url.match(TwitterRegex)

  if (match && match.length >= 3) {
    const tweetId = match[2]
    return tweetId || null
  }

  return null
}

const createHiddenTweetContainer = () => {
  const container = document.createElement('div')
  container.style.position = 'absolute'
  container.style.left = '-10000px'
  container.style.top = '0'
  container.style.width = '540px'
  container.style.pointerEvents = 'none'
  document.body.append(container)
  return container
}

/** Creates markdown containing tweet iframe HTML generated by the Twitter widgets script. */
export const createTweetEmbedMarkdown = async (url: string, isDarkMode: boolean): Promise<string | null> => {
  if (!validateTwitterUrl(url) || !twttr?.widgets?.createTweet) {
    return null
  }

  const tweetId = getTweetIdFromUrl(url)

  if (!tweetId) {
    return null
  }

  const container = createHiddenTweetContainer()

  try {
    const tweetElement = await twttr.widgets.createTweet(tweetId, container, {
      width: '350px',
      theme: isDarkMode ? 'dark' : 'light',
    })

    const embedHtml = tweetElement.outerHTML

    return `${EMBED_MARKDOWN_PREFIX}${embedHtml}${EMBED_MARKDOWN_SUFFIX}`
  } finally {
    container.remove()
  }
}

/** Toolbar action for inserting YouTube iframe embeds in markdown. */
export const MdxInsertVideoButton = () => {
  const insertMarkdown = usePublisher(insertMarkdown$)
  const { toast } = useNotification()

  const onSubmit = (url: string) => {
    const markdown = createYoutubeEmbedMarkdown(url)

    if (!markdown) {
      toast({
        status: 'error',
        title: t('Invalid video URL'),
        description: t('Please try again'),
      })
      return
    }

    insertMarkdown(markdown)
  }

  return (
    <DialogButton
      tooltipTitle={t('Insert video')}
      buttonContent={<PiYoutubeLogo size={16} />}
      dialogInputPlaceholder={t('Youtube URL')}
      submitButtonTitle={t('Insert')}
      onSubmit={onSubmit}
    />
  )
}

/** Toolbar action for inserting tweet embeds as markdown-compatible iframe HTML. */
export const MdxInsertTweetButton = () => {
  const insertMarkdown = usePublisher(insertMarkdown$)
  const { toast } = useNotification()
  const isDarkMode = useDarkMode()

  const onSubmit = async (url: string) => {
    const markdown = await createTweetEmbedMarkdown(url, isDarkMode)

    if (!markdown) {
      toast({
        status: 'error',
        title: t('Invalid tweet URL'),
        description: t('Please try again'),
      })
      return
    }

    insertMarkdown(markdown)
  }

  return (
    <DialogButton
      tooltipTitle={t('Insert tweet')}
      buttonContent={<PiXLogo size={16} />}
      dialogInputPlaceholder={t('Tweet URL')}
      submitButtonTitle={t('Insert')}
      onSubmit={(url) => {
        onSubmit(url).catch(() => undefined)
      }}
    />
  )
}
