export enum ApolloErrors {
  BAD_USER_INPUT = 'BAD_USER_INPUT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_FUNDING_AMOUNT = 'INVALID_FUNDING_AMOUNT',
  WALLET_UNREACHABLE = 'WALLET_UNREACHABLE',
  NON_ACTIVE_PROJECT = 'NON_ACTIVE_PROJECT',
  REWARD_OUT_OF_STOCK = 'REWARD_OUT_OF_STOCK',
}
