export const DefaultMetaTitle = 'Geyser | Bitcoin Crowdfunding Platform'
export const DefaultMetaImage = 'https://storage.googleapis.com/geyser-projects-media/app/seo.png'
export const DefaultMetaDescription = 'Support bitcoin projects you want to see come to life. Join the crowdfund now!'
export const DefaultMetaType = 'website'
export const DefaultMetaTwitterCard = 'summary_large_image'
export const DefaultMetaTwitterSite = 'geyserfund'
