export const noFeeProjects = [
  'ayudaalosjvenesalfuturo',
  'bff',
  // 'anonymal',
  // 'chesskingdoms',
  'bloggingbitcoingeyser',
  'blip',
  'bwbip47',
  'amityageacademy',
  'lahoracripto',
  // 'designerclothingstorebitcoin',
  // 'blixt',
  'alphabettingthefirsthedgefundbasedonfantokens',
  'africanwomenattendingafricabitcoinconference',
  'jvenesenaccinlimpiezaenlacomunidad',
  'alephcitadelpatagonia',
  'ataco',
  'citadel',
  'murdawkmedia',
  'mostro',
  'prosoccerteaminhawaii',
  'swissbitcoinpay',
  'nodeyez',
  'creeksidesummercamp',
  'thecryptoc0up1e',
  // 'greekbitcoinworkshop',
  'sovereignrancher',
  'nobsbitcoin',
  'bitcointradingcards',
  // 'dirtycointhecontroversy',
  // 'behindbitcoinmining',
  // 'bitcoinkids',
  // 'bitcoinballersacademy',
  'latinodos',
  'btcmap',
  'bitcoinacademy',
  'lndgxyzgui20',
  'hillrun',
  'bitdevsacademy',
  'homelesswarmwear',
  'proofofresilience',
  'bitcoin60seconds',
  // 'ionio',
  // 'anewgoatproject',
  'geyser',
  'thelastrevolution',
  'betweentwoasics',
  'trustdocumentary',
  'binkbonkbank',
  'bitcointwitter',
  'bitcoinracing',
  'earthquakereliefturkey',
]
