import { IProjectBlock, IProjectDetail } from '../../../interfaces';
const projectBlocks: IProjectBlock[] = [
  {
    key: 'description1',
    title: 'The Story',
    body: [
      "Is Bitcoin as an alternative to the fiat financial system, possibly society's last chance for a socio-economic revolution? ",
      'As of May  2022, 1.7 billion people have no bank account.',
      '200 million have a bitcoin wallet and of those, 106 million own bitcoin. 53 million worldwide use it on a daily basis to trade or as a means of payment.',
      'Why is this the case? Which circumstances have led to this and will Bitcoin subsequently establish itself as an alternative to the fiat financial system?',
      'We will accompany a film crew along the Pan American Highway through different states, cities, towns of the USA.',
      'Along the road we will explore and delve into our present socio-economic status quo as we also cast an eye upon the future and the resulting question: „Will Bitcoin fix this?“ ',
      'We will be stopping in different states and lands to interview toolmakers, developers, philosophers, sociologists, politicians, futurologists and human rights activists. Arriving in San Francisco we get a closer look into the world of Bitcoin Maxis. Who are they, what can we  learn from them and what is the difference between investors and average Bitcoiners? ',
      'Street interviews across the country give insights into the lives of ordinary people living with and from Bitcoin. The idea and relevance of the decentralized networks will be examined and planned projects will be made clear. ',
      'Help comes in the form of an outsider which is not part of the crypto scene. He gives critical- philosophical and also entertaining points of view and provokes easily understandable answers to intrinsic questions, as we confront myths and deliberately spread misinformation about Bitcoin and its benefit to people around the globe.',
    ],
    blockType: 'PL',
  },
  {
    key: 'description12',
    title: 'The Realization',
    body: [
      '**Our intention is to shoot this November. At the end of this year, all team members will have time to devote exclusively to the project.**',
      'This Journey into the Unknown serves as a metaphor for finding unanswered societal relevant questions that will need to be answered as we move to a future with a strong bitcoin presence. ',
      'America, idealized as the land of the free, will be documented in its cultural-politic ambivalence through expressive look & feel metaphors accompanied with an exemplary soundtrack.',
      'Alternately we find ourselves in a rhythm of road movie visuals, digital art, interviews, and creative interludes. ',
      'The desire for independence will be commented on in a contemporary poetic approach and with critical eye to peripheral themes as well. Fundamental to this we learn from normal people, who use bitcoin to survive and participate in the financial system. ',
      'In the style of Cinéma vérité interview partners answer key questions and share their truth about bitcoin and its possible future. ',
    ],
    images: [9],
    blockType: 'PL',
  },
  {
    key: 'description2',
    title: 'The Team',
    body: [
      'Nela Biedermann is responsible for the idea, script, direction and parts of art direction, also she is executive producer. ',
      'In collaboration with Studio Koa Berlin https://studiokoa.berlin, an all female creative production startup and  with a cameraperson who takes documentary imagery to the next level, the current team of 6 is well positioned. During the funding phase the team will be introduced.',
    ],
    blockType: 'PL',
  },
  {
    key: 'description3',
    title: 'Examples for Visual language & Moodboard ',
    body: [],
    images: [1, 2],
    blockType: 'PL',
  },
  {
    key: 'examples',
    title: '',
    body: [],
    images: [3, 4],
    blockType: 'PL',
  },
  {
    key: 'description7',
    title: 'Our Milestones',
    body: [
      '1. **3000** - for pre-production: pay an orga helper for planning the travel and interview requests, for first local interviews',
      '2. **10.000** - to book flights and some accommodation',
      '3. **15.000** - to fly over to the USA and prepare for the shooting',
      '4. **25.000** - all above including renting or buying our Bus ',
      '5. **From 70.000 to 100.000** - film 3 - 6 weeks in the USA',
      '6. **100.000** - first rough cut ',
    ],
    blockType: 'PL',
  },
  {
    key: 'description4',
    title: 'Side-projects',
    body: [
      'The animated film „the grumpy bitfish“, which Nela created from watercolor paintings, transformed into digital pictures and animated it, will be further developed and integrated into the documentary. I am looking for motion designers who want to rework its surface and provide an alternate ending of the current story.  Of course the  work will be rewarded.',
    ],
    images: [5, 6],
    blockType: 'PL',
  },
  {
    key: 'description4',
    title: '',
    body: [
      'The Berlin photographer https://www.louiseamelie.com will transform impressions, experiences, chaos and love during the making of the road movie into a photo exhibition with a photo book. ',
      'During the production phase, we want to collect unadulterated footage from Bitcoin users worldwide with a focus on Africa and incorporate it into the documentary. We are launching a call for this..  ',
    ],
    blockType: 'PL',
  },
  {
    key: 'aboutmephotos',
    title: 'About Me',
    body: [],
    images: [10],
    blockType: 'PL',
  },
  {
    key: 'description5',
    title: '',
    body: [
      "I wished for nothing more than that 2022 would finally begin and the ballast of the previous year would dissolve into goodwill. My dragon tree, which I christened Lill Covid on May 7, 2020, cares little. I water, it grows, that's the deal. This date was my prelude to a personal wake up call.",
      'An accident and chaos provoked by Covid are put into perspective in the face of the Russia - Ukraine war. ',
      'I have questions. Quo vadis humanity, quo vadis homo economicus?',
      'After months of Covid isolation, I was simply without hope. ',
      'My bank account strongly reinforced this impression. I was not good with money, it said.',
      'No growth, the bank proclaimed.',
      "I wouldn't set long-term goals, the advisor said. I wasn't putting enough away for retirement, my pension report roared.",
      "On a social level, I like to be generous and don't want to put money at the forefront of my agenda. ",
      'With small trading successes that have enabled me to bear the additional costs of my rehabilitation, I get serious: why do we trust the status quo? How do pervasive political and economic crises affect me, my family and their future? Are there alternatives?',
      'I read about ideas of social justice for all and do basic research on the origins of our money.',
      'The fiat financial system seems to have evolved to be anything but fair.',
      'It calls my altruism not worthwhile and punishes any kind of nonconformist behavior with credit unworthiness. ',
      'The quest to provide sufficiently for our well-being becomes a fear issue and the engine of a perpetual, paralyzing hunt for economic security. In the course of a human life, stress and ambivalence advance to an avoidance strategy. Remaining in our protective attitude, we consume and compensate, compromise and compensate again. ',
      'We work because we want to take responsibility for our own lives. ',
      'At some point, however, we work for a life that we no longer question out of habit, and we do so for a wage that often does not reflect the value of our labor. ',
      'Great doubts about this doctrine arise and I decide to explore Bitcoin in documentary form. ',
      'In times of openly fought economic wars, neo-colonialism and misanthropic global politics, I am interested in shedding more light on the benefits of Bitcoin for the majority of society.',
      'In doing so, it seems important to me to interview the people who consider the digital currency to be the most important tool for financial inclusion and economic equality about their vision of the future with it as a dominant currency. ',
      'Therefore, I would like to know how Bitcoin will be used in the future.',
      'I want to know how Bitcoin is being used around the world as a rescue anchor in the absence of inclusion in the financial market and without having a bank account. ',
      'What exactly does Bitcoin do better? How does it do it? What does it take to achieve "better"? ',
      'In 2018 I completed my education as a producer at Filmhaus Babelsberg. I gained many years of experience as a freelancer in the field of short film, feature film, at festivals and in the preparation of documentaries. I was able to work in all positions in areas of production and directing. ',
      'My strengths lie in visual conception and script development, writing fictional stories but also essays focusing on our socio-economic status quo, visual arts, especially painting and drawing, sculpture and digital art, as well as digital painting and a bit of 3D animation, drawing with ProCreate and Blender. ',
      'I recently gave up a secure job in a large cultural institution to focus on implementing my own ideas. ',
      'As a German-Senegalese, a black woman in a white economy, I have a differentiated experience on many topics. I hope that this perspective will complement and broaden the subject.',
      "In the field of film alone, I can synthesize creative energy from my life's journey, from all my experiences and ideas, and carry them into the world in my own film language. ",
      '[https://m.imdb.com/name/nm3479489/filmotype/assistant_director?ref_=m_nmfm_1](https://m.imdb.com/name/nm3479489/filmotype/assistant_director?ref_=m_nmfm_1)',
      '[https://www.crew-united.com/de/Daniela-Nela-Biedermann_683503.html](https://www.crew-united.com/de/Daniela-Nela-Biedermann_683503.html)',
      '**Awards**',
      'Rhode Island IFF - First Place ',
      'Filmbewertungsstelle Wiesbaden FBW- Short of the month',
      'Internationaler NOMOS/Shotgun festival - First place ',
    ],
    images: [7, 8],
    blockType: 'PL',
  },
];

const projectDetails: IProjectDetail = {
  problem: '',
  idea: 'We need your help to be  cinematic chroniclers and to create extraordinary interviews and images of  this unique moment in history: a possible socio- economic revolution.',
  ownerIntro:
    'I recently gave up a secure job in a large cultural institution to focus on implementing my own ideas.',
  blocks: projectBlocks,
};

const projectName: string = 'thelastrevolution';

export const Nela = { projectBlocks, projectDetails, projectName };
